# Generated by Django 2.0.1 on 2018-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('institution', '机构'), ('school', '高校'), ('own', '个人')], default='pxjg', max_length=20, verbose_name='机构类别'),
        ),
    ]
