# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180321_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('url', models.URLField(default='', max_length=100, verbose_name='链接')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='图像')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('code', models.CharField(max_length=30, verbose_name='验证码')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '忘记密码'), ('update_email', '邮箱重置')], default='register', max_length=20, verbose_name='验证码类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
